# runs when 1. is triggered
name: Modify version number and add "dev-" prefix

on:
  # Automatic trigger when pushing tags
  # push:
  #   branches:
  #     - "!*"
  #   tags:
  #     - 'v*'

  # Manual trigger from the UI
  workflow_dispatch:
    inputs:
      message:
        description: 'Build description'

  # Dependency to a forking workflow
  workflow_run:
    workflows: ["1. Generate version number (trigger on push)"]
    type:
      - complete

      
